const List<String> allSkills = [
  'Graphic Design',
  'Flutter Development',
  'Python Programming',
  'Freelancing',
  'SEO',
  'Video Editing',
  'Web Development',
  'Digital Marketing',
  'UI/UX Design',
  'React Development',
  'Android Development',
  'iOS Development',
  'Machine Learning',
  'Data Science',
  'Artificial Intelligence',
  'Content Writing',
  'Social Media Management',
  'JavaScript',
  'Node.js',
  'Angular Development',
  'Cloud Computing',
  'AWS',
  'DevOps',
  'Blockchain Development',
  'Cyber Security',
  'Game Development',
  'Unity 3D',
  'Database Management',
  'SQL',
  'MongoDB',
  'WordPress Development',
  'PHP Development',
  'Java Programming',
  'C++ Programming',
  'Swift Programming',
  'Kotlin Development',
  'Data Analytics',
  'Business Intelligence',
  'Digital Photography',
  '3D Modeling',
  'Animation',
  'Music Production',
  'Language Teaching',
  'Public Speaking',
  'Project Management',
  'Product Management',
  'Agile Methodology',
  'Quality Assurance',
  'Technical Writing',
  'Mobile App Design',
];

// For fast index lookup everywhere
final Map<String, int> skillToIndex = {
  for (int i = 0; i < allSkills.length; i++) allSkills[i].toLowerCase(): i,
};