// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVdyjI-A2b-J1V_ELunnAyDCyXm5MdmFU',
    appId: '1:588926423466:web:954bca073fd6b545031bd3',
    messagingSenderId: '588926423466',
    projectId: 'fyp-skill-buddy',
    authDomain: 'fyp-skill-buddy.firebaseapp.com',
    storageBucket: 'fyp-skill-buddy.firebasestorage.app',
    measurementId: 'G-ZXETQSGV74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx2pawIaMBX616YpL3TvjtxnLgd2rLP5w',
    appId: '1:588926423466:android:734255f019985362031bd3',
    messagingSenderId: '588926423466',
    projectId: 'fyp-skill-buddy',
    storageBucket: 'fyp-skill-buddy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5FrpD0XB_bsjNQbVvk_nCTdvLVRB5kZc',
    appId: '1:588926423466:ios:4430cae86708df66031bd3',
    messagingSenderId: '588926423466',
    projectId: 'fyp-skill-buddy',
    storageBucket: 'fyp-skill-buddy.firebasestorage.app',
    iosBundleId: 'com.example.skillBuddyFyp',
  );
}
